name: PRJNA692319
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - biopython=1.79
  - entrez-direct=16.2
  - fastp=0.23.2
  - jupyterlab>=3
  - mafft=7.490
  - mamba
  - minimap2=2.23
  - pandas=1.3.4
  - pysam=0.17.0
  - python=3.9
  - samtools=1.14
  - snakemake=6.12.3
  - sra-tools=2.11.0
  - ivar=1.3.1
